name: Nix Configuration Validation

on:
  push:
    branches: [ main ]
    paths-ignore:
      - "docs/**"
      - ".github/workflows/docs.yml"
  pull_request:
    branches: [ main ]

jobs:
  check-nix-flake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Setup Nix Cache
        uses: DeterminateSystems/flakehub-cache-action@main

      - name: Check Flake Inputs
        run: nix flake check

  check-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Setup Nix Cache
        uses: DeterminateSystems/flakehub-cache-action@main

      - name: Check Nix formatting
        run: |
          nix run nixpkgs#nixfmt-rfc-style -- --check $(find . -name "*.nix" -type f)

  check-deadlinks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Setup Nix Cache
        uses: DeterminateSystems/flakehub-cache-action@main

      - name: Check for dead links in Nix files
        run: |
          nix run nixpkgs#deadnix -- . --fail
